### ISSUE TITLE
Missing com.transitionseverywhere.TransitionSet

### ISSUE THREAD

**Issue by Drusantia** [siralam/DropDownView#4]
Hi,
I think there's a library dependency for this that isn't resolved.
I get this exception when I tap on the doropdown:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ((((__ package name was here __)))), PID: 14955
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/transitionseverywhere/TransitionSet;
        at com.asksira.dropdownview.DropDownView.expand(DropDownView.kt:409)
        at com.asksira.dropdownview.DropDownView.toggle(DropDownView.kt:389)
        at com.asksira.dropdownview.DropDownView$init$1.onClick(DropDownView.kt:268)
        at android.view.View.performClick(View.java:6891)
        at android.view.View$PerformClick.run(View.java:26083)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.transitionseverywhere.TransitionSet" on path: DexPathList[[zip file ((((__ dex paths were here__))))]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.asksira.dropdownview.DropDownView.expand(DropDownView.kt:409) 
        at com.asksira.dropdownview.DropDownView.toggle(DropDownView.kt:389) 
        at com.asksira.dropdownview.DropDownView$init$1.onClick(DropDownView.kt:268) 
        at android.view.View.performClick(View.java:6891) 
        at android.view.View$PerformClick.run(View.java:26083) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by Drusantia** [comment]
Note: 
adding 
implementation "com.andkulikov:transitionseverywhere:1.8.0"
to the gradle solves it but it's still a hidden dependency

**Comment by 100rabhkr** [comment]
Was facing the same issue thanks @Drusantia for the temporary resolution

**Comment by ZakariaJawas** [comment]
@Drusantia solution worked fine, but this problem raised up again after i migrated to **AndroidX**
**UPDATE**
I managed to fix this by cloning the whole project, migrating to androidX, updating com.andkulikov:transitionseverywhere version and import the andoridX classes of that library then import the **DropDownView** as a module in my project
i guess we have to wait until the developer updates the library so it can be used through the project's **Gradle** file

**Comment by unix14** [comment]
DEVELOPER!! ATTENTION!!

pls release a fix for this issue ASAP

**Comment by siralam** [comment]
Updated to AndroidX and specified the dependency of transitionseverywhere in README.
