### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics

### ISSUE THREAD

**Issue by CristianRP** [siralam/DropDownView#7]
Hi, 
This error ocurred when add DropDownView to my fragment's layout. 

```
InflateException: Binary XML file line #306: Binary XML file line #306: Error inflating class com.asksira.dropdownview.DropDownView. 
```
And the cause seems to be a `NoClassDefFoundError Lkotlin/jvm/internal/Intrinsics`

Here is a part of the log: 
```
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/jvm/internal/Intrinsics;
        at com.asksira.dropdownview.DropDownView.<init>(DropDownView.kt)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:656) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:798) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:869) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:872) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126) 
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95) 
```

**Comment by CristianRP** [comment]
Solution, add kotlin to gradle.

`implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$versions.kotlin_version" `
