### ISSUE TITLE
Binary XML file line #18: Binary XML file line #18: Error inflating class com.asksira.dropdownview.DropDownView

### ISSUE THREAD

**Issue by 201402407** [siralam/DropDownView#9]
Caused by: android.view.InflateException: Binary XML file line #18: Binary XML file line #18: Error inflating class com.asksira.dropdownview.DropDownView
     Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class com.asksira.dropdownview.DropDownView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:461)
        at android.app.Activity.setContentView(Activity.java:2737)
        at com.gaze.rkdus.a2019_epis_tufu4.SplashActivity.onCreate(SplashActivity.java:30)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

How do I solve it?

SplashActivity.line 30
setContentView(R.layout.activity_splash);

activity_splash:

<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/colorWhite"
    android:orientation="vertical"
    tools:context=".SplashActivity">

    <ImageView
        android:id="@+id/splash"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone"
        />

    <com.asksira.dropdownview.DropDownView
        android:id="@+id/dropdownview"
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>
</FrameLayout>

**Comment by madhurawanniarachchi** [comment]
Did your problem solve? I have faced same problem too.

**Comment by shivanshu53** [comment]
how to solve this issue ?

**Comment by basemosama** [comment]
Hey ,
try adding these dependencies to your build.gradle file

>     implementation 'com.asksira.android:dropdownview:1.0.3'
>     implementation 'com.andkulikov:transitionseverywhere:1.8.0'
>     implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.61'
>

**Comment by siralam** [comment]
After I know how to hide these extra dependencies, I would update the library so that you guys don't need to include these by yourself. Sorry about that!

**Comment by siralam** [comment]
Dulicate of #4.
